---
- name: configure-realmd | Create /etc/realmd.conf
  blockinfile:
    path: "{{ realmd_conf }}"
    create: true
    backup: true
    owner: root
    group: root
    mode: 0644
    block: |
      [users]
      default-home = /home/%U
      default-shell = /bin/bash

      [active-directory]
      default-client = sssd
      os-name = {{ ansible_distribution }}
      os-version = {{ ansible_distribution_major_version }}

      [service]
      automatic-install = no

      [{{ realm_domain }}]
      fully-qualified-names = no
      automatic-id-mapping = yes
      user-principal = yes
      manage-system = no
