---
- name: configure-sssd | Configure the sssd.conf For the Domain
  blockinfile:
    path: "{{ sssd_conf }}"
    create: true
    backup: true
    owner: root
    group: root
    mode: 0600
    block: |
      [sssd]
      domains = {{ realm_domain }}
      config_file_version = 2
      services = nss, pam

      [domain/{{ realm_domain }}]
      ad_domain = {{ realm_domain }}
      krb5_realm = {{ krb5_default_realm }}
      realmd_tags = joined-with-adcli
      cache_credentials = True
      id_provider = ad
      krb5_store_password_if_offline = True
      default_shell = /bin/bash
      ldap_id_mapping = True
      use_fully_qualified_names = False
      fallback_homedir = /home/%u
      simple_allow_users = $
      access_provider = ad
  notify: restart sssd
